version: "3.9"

services:
  php:
    build: .
    container_name: wpcr_php
    volumes:
      - ./:/var/www/html
      - /var/log/apache2/wpcr:/var/log/apache2
      - vardata:/var/www/html/var
    ports:
      - "9727:80"
    depends_on:
      - db
    networks:
      wpcr_net:

  db:
    image: mysql:5.7
    container_name: wpcr_db
    environment:
      MYSQL_ROOT_PASSWORD: sd496gf45r87532ktrdeog
      MYSQL_DATABASE: wpcr
      MYSQL_USER: dbo
      MYSQL_PASSWORD: test123
    volumes:
      - "./etc/sql:/docker-entrypoint-initdb.d"
    networks:
      wpcr_net:

networks:
  wpcr_net:
    driver: bridge

volumes:
  vardata: